### ISSUE TITLE
在编译base.less文件的时候报错

### ISSUE THREAD

**Issue by ghost** [aliceui/aliceui.org#36]
如题，在使用Crunch编译base.less的时候报了一个语法错误：

``` js
Compiler Errors
Syntax Error on line 32 (Line: 32)
```

看了一下，是这段代码出错了

``` css
/* 要注意表单元素并不继承父级 font 的问题 */
body,button,input,select,textarea{
    font:12px/1.5 tahoma,arial,\5b8b\4f53;
}
```

在less中`/`表示的是一个运算符，看[lesscss.net ](http://www.lesscss.net)中有避免编译这一节，所以就将上面的代码改了一下：

``` css
/* 要注意表单元素并不继承父级 font 的问题 */
body,button,input,select,textarea{
    font:~'12px/1.5 tahoma,arial,\5b8b\4f53';
}
```

这样子就不会出现`Syntax Error`这个错误了。

> 问题：有没有其它的方案可以解决这种需要反编译的符号？
