### ISSUE TITLE
请问字体设置的依据是？

### ISSUE THREAD

**Issue by afc163** [aliceui/aliceui.org#40]
> 迁移的 issue

@jsw0528:

``` css
body {
    font:12px/1.5 tahoma,arial,Hiragino Sans GB,"Microsoft Yahei",\5b8b\4f53;
}
```

`arial` 应该都会有吧？那`Microsoft Yahei`还能被应用么？
